version: '2'
services:
  taozi-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: taozi-mysql
    image: taozi-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    hostname: ${mysql_host}
    ports:
      - ${mysql_port}:3306
    volumes:
      - ${mysql_data}:/var/lib/mysql

  taozi-redis:
    container_name: taozi-redis
    restart: always
    image: redis:5.0
    hostname: ${redis_host}
#    ports:
#      - ${redis_port}:6379

  taozi-be:
    restart: on-failure
    depends_on:
      - taozi-mysql
      - taozi-redis
    container_name: taozi-be
    image: taozi-be:0.2.5
    hostname: ${taozi_host}
#    ports:
#      - ${taozi_port}:8081
#    volumes:
#      - ${taozi_config}:/taozi-be/config

  taozi-nginx:
    image: nginx:latest
    container_name: taozi-nginx
    depends_on:
      - taozi-be
    links:
      - taozi-be
    ports:
      - ${taozi_port}:80
    volumes:
      - "./docker_config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker_config/nginx/conf.d:/etc/nginx/conf.d"

