CREATE TABLE `basic_road` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `road_code` varchar(40) DEFAULT NULL COMMENT '路线编码',
  `road_name` varchar(100) DEFAULT NULL COMMENT '路线名称',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路线长度（千米）',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `basic_segment` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `segment_code` varchar(40) DEFAULT NULL COMMENT '区间编码',
  `road_code` varchar(40) DEFAULT NULL COMMENT '路线编码',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '区间长度（千米）',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `basic_unit` (
  `unit_code` varchar(40) NOT NULL COMMENT '路段编码, 主键',
  `road_code` varchar(40) DEFAULT NULL COMMENT '路线编码',
  `segment_code` varchar(40) DEFAULT NULL COMMENT '区间编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '路段起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '路段终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度（千米）',
  `road_grade` varchar(5) DEFAULT NULL COMMENT '技术等级',
  `subgrade_width` decimal(10,2) DEFAULT NULL COMMENT '路基宽度（米）',
  `pavement_width` decimal(10,2) DEFAULT NULL COMMENT '路面宽度（米）',
  `pavement_type` varchar(5) DEFAULT NULL COMMENT '路面类型',
  `is_toll` int(11) DEFAULT NULL COMMENT '是否收费公路',
  `district` varchar(40) DEFAULT NULL COMMENT '所属政区/区域',
  `district_grade` varchar(40) DEFAULT NULL COMMENT '行政等级',
  `maintain` varchar(40) DEFAULT NULL COMMENT '管养单位',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`unit_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_bci_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `hd1` varchar(40) DEFAULT NULL COMMENT '涵洞 1',
  `hd2` varchar(40) DEFAULT NULL COMMENT '涵洞 2',
  `hd3` varchar(40) DEFAULT NULL COMMENT '涵洞 3',
  `hd4` varchar(40) DEFAULT NULL COMMENT '涵洞 4',
  `hd5` varchar(40) DEFAULT NULL COMMENT '涵洞 5',
  `ql1` varchar(40) DEFAULT NULL COMMENT '桥梁 1',
  `ql2` varchar(40) DEFAULT NULL COMMENT '桥梁 2',
  `ql3` varchar(40) DEFAULT NULL COMMENT '桥梁 3',
  `ql4` varchar(40) DEFAULT NULL COMMENT '桥梁 4',
  `ql5` varchar(40) DEFAULT NULL COMMENT '桥梁 5',
  `sd1` varchar(40) DEFAULT NULL COMMENT '隧道 1',
  `sd2` varchar(40) DEFAULT NULL COMMENT '隧道 2',
  `sd3` varchar(40) DEFAULT NULL COMMENT '隧道 3',
  `sd4` varchar(40) DEFAULT NULL COMMENT '隧道 4',
  `sd5` varchar(40) DEFAULT NULL COMMENT '隧道 5',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_pbi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `pbi_tc_code` varchar(20) DEFAULT NULL COMMENT 'PBI 等级',
  `pb` double DEFAULT NULL COMMENT 'PB',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_pci_lq_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `dr` varchar(40) DEFAULT NULL COMMENT '破损率',
  `jl_q` varchar(40) DEFAULT NULL COMMENT '龟裂轻',
  `jl_m` varchar(40) DEFAULT NULL COMMENT '龟裂中',
  `jl_z` varchar(40) DEFAULT NULL COMMENT '龟裂重',
  `kzlf_q` varchar(40) DEFAULT NULL COMMENT '块状裂缝轻',
  `kzlf_z` varchar(40) DEFAULT NULL COMMENT '块状裂缝重',
  `zxlf_q` varchar(40) DEFAULT NULL COMMENT '纵向裂缝轻',
  `zxlf_z` varchar(40) DEFAULT NULL COMMENT '纵向裂缝重',
  `hxlf_q` varchar(40) DEFAULT NULL COMMENT '横向裂缝轻',
  `hxlf_z` varchar(40) DEFAULT NULL COMMENT '横向裂缝重',
  `kc_q` varchar(40) DEFAULT NULL COMMENT '坑槽轻',
  `kc_z` varchar(40) DEFAULT NULL COMMENT '坑槽重',
  `ss_q` varchar(40) DEFAULT NULL COMMENT '松散轻',
  `ss_z` varchar(40) DEFAULT NULL COMMENT '松散重',
  `cx_q` varchar(40) DEFAULT NULL COMMENT '沉陷轻',
  `cx_z` varchar(40) DEFAULT NULL COMMENT '沉陷重',
  `cz_q` varchar(40) DEFAULT NULL COMMENT '车辙轻',
  `cz_z` varchar(40) DEFAULT NULL COMMENT '车辙重',
  `blyb_q` varchar(40) DEFAULT NULL COMMENT '波浪拥包轻',
  `blyb_z` varchar(40) DEFAULT NULL COMMENT '波浪拥包重',
  `fy` varchar(40) DEFAULT NULL COMMENT '泛油',
  `kzxb` varchar(40) DEFAULT NULL COMMENT '块状修补',
  `tzxb` varchar(40) DEFAULT NULL COMMENT '条状修补',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_pci_sn_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `dr` varchar(40) DEFAULT NULL COMMENT '破损率',
  `psb_q` varchar(40) DEFAULT NULL COMMENT '破碎板轻',
  `psb_z` varchar(40) DEFAULT NULL COMMENT '破碎板重',
  `lf_q` varchar(40) DEFAULT NULL COMMENT '裂缝轻',
  `lf_m` varchar(40) DEFAULT NULL COMMENT '裂缝中',
  `lf_z` varchar(40) DEFAULT NULL COMMENT '裂缝重',
  `bjdl_q` varchar(40) DEFAULT NULL COMMENT '板角断裂轻',
  `bjdl_m` varchar(40) DEFAULT NULL COMMENT '板角断裂中',
  `bjdl_z` varchar(40) DEFAULT NULL COMMENT '板角断裂重',
  `ct_q` varchar(40) DEFAULT NULL COMMENT '错台轻',
  `ct_z` varchar(40) DEFAULT NULL COMMENT '错台重',
  `gq` varchar(40) DEFAULT NULL COMMENT '拱起',
  `bjbl_q` varchar(40) DEFAULT NULL COMMENT '边角剥落轻',
  `bjbl_m` varchar(40) DEFAULT NULL COMMENT '边角剥落中',
  `bjbl_z` varchar(40) DEFAULT NULL COMMENT '边角剥落重',
  `jflsh_q` varchar(40) DEFAULT NULL COMMENT '接缝料损坏轻',
  `jflsh_z` varchar(40) DEFAULT NULL COMMENT '接缝料损坏重',
  `kd` varchar(40) DEFAULT NULL COMMENT '坑洞',
  `jn` varchar(40) DEFAULT NULL COMMENT '唧泥',
  `lg` varchar(40) DEFAULT NULL COMMENT '露骨',
  `kzxb` varchar(40) DEFAULT NULL COMMENT '块状修补',
  `tzxb` varchar(40) DEFAULT NULL COMMENT '条状修补',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_pssi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `li` double DEFAULT NULL COMMENT 'Li',
  `l0` double DEFAULT NULL COMMENT 'L0',
  `l01` double DEFAULT NULL COMMENT 'L01',
  `l02` double DEFAULT NULL COMMENT 'L02',
  `l03` double DEFAULT NULL COMMENT 'L03',
  `l04` double DEFAULT NULL COMMENT 'L04',
  `l05` double DEFAULT NULL COMMENT 'L05',
  `l06` double DEFAULT NULL COMMENT 'L06',
  `l07` double DEFAULT NULL COMMENT 'L07',
  `l08` double DEFAULT NULL COMMENT 'L08',
  `l09` double DEFAULT NULL COMMENT 'L09',
  `l10` double DEFAULT NULL COMMENT 'L10',
  `l11` double DEFAULT NULL COMMENT 'L11',
  `l12` double DEFAULT NULL COMMENT 'L12',
  `l13` double DEFAULT NULL COMMENT 'L13',
  `l14` double DEFAULT NULL COMMENT 'L14',
  `l15` double DEFAULT NULL COMMENT 'L15',
  `l16` double DEFAULT NULL COMMENT 'L16',
  `l17` double DEFAULT NULL COMMENT 'L17',
  `l18` double DEFAULT NULL COMMENT 'L18',
  `l19` double DEFAULT NULL COMMENT 'L19',
  `l20` double DEFAULT NULL COMMENT 'L20',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_pwi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `mpd_avg_left` double DEFAULT NULL COMMENT 'MPD_AVG_LEFT',
  `mpd_avg_center` double DEFAULT NULL COMMENT 'MPD_AVG_CENTER',
  `mpd_avg_right` double DEFAULT NULL COMMENT 'MPD_AVG_RIGHT',
  `mpd_left01` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT01',
  `mpd_center01` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER01',
  `mpd_right01` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT01',
  `mpd_left02` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT02',
  `mpd_center02` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER02',
  `mpd_right02` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT02',
  `mpd_left03` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT03',
  `mpd_center03` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER03',
  `mpd_right03` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT03',
  `mpd_left04` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT04',
  `mpd_center04` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER04',
  `mpd_right04` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT04',
  `mpd_left05` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT05',
  `mpd_center05` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER05',
  `mpd_right05` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT05',
  `mpd_left06` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT06',
  `mpd_center06` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER06',
  `mpd_right06` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT06',
  `mpd_left07` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT07',
  `mpd_center07` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER07',
  `mpd_right07` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT07',
  `mpd_left08` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT08',
  `mpd_center08` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER08',
  `mpd_right08` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT08',
  `mpd_left09` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT09',
  `mpd_center09` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER09',
  `mpd_right09` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT09',
  `mpd_left10` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT10',
  `mpd_center10` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER10',
  `mpd_right10` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT10',
  `mpd_left11` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT11',
  `mpd_center11` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER11',
  `mpd_right11` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT11',
  `mpd_left12` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT12',
  `mpd_center12` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER12',
  `mpd_right12` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT12',
  `mpd_left13` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT13',
  `mpd_center13` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER13',
  `mpd_right13` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT13',
  `mpd_left14` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT14',
  `mpd_center14` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER14',
  `mpd_right14` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT14',
  `mpd_left15` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT15',
  `mpd_center15` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER15',
  `mpd_right15` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT15',
  `mpd_left16` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT16',
  `mpd_center16` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER16',
  `mpd_right16` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT16',
  `mpd_left17` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT17',
  `mpd_center17` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER17',
  `mpd_right17` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT17',
  `mpd_left18` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT18',
  `mpd_center18` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER18',
  `mpd_right18` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT18',
  `mpd_left19` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT19',
  `mpd_center19` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER19',
  `mpd_right19` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT19',
  `mpd_left20` float(10,3) DEFAULT NULL COMMENT 'MPD_LEFT20',
  `mpd_center20` float(10,3) DEFAULT NULL COMMENT 'MPD_CENTER20',
  `mpd_right20` float(10,3) DEFAULT NULL COMMENT 'MPD_RIGHT20',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_rdi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `rd_avg` double DEFAULT NULL COMMENT 'RD',
  `rd_avg_left` double DEFAULT NULL COMMENT 'RD_LEFT',
  `rd_avg_right` double DEFAULT NULL COMMENT 'RD_RIGHT',
  `rd_max_avg` double DEFAULT NULL COMMENT 'RD_MAX',
  `rd_max_left` double DEFAULT NULL COMMENT 'RD_MAX_LEFT',
  `rd_max_right` double DEFAULT NULL COMMENT 'RD_MAX_RIGHT',
  `rd_left01` double DEFAULT NULL COMMENT 'RD_LEFT01',
  `rd_right01` double DEFAULT NULL COMMENT 'RD_RIGHT01',
  `rd_left02` double DEFAULT NULL COMMENT 'RD_LEFT02',
  `rd_right02` double DEFAULT NULL COMMENT 'RD_RIGHT02',
  `rd_left03` double DEFAULT NULL COMMENT 'RD_LEFT03',
  `rd_right03` double DEFAULT NULL COMMENT 'RD_RIGHT03',
  `rd_left04` double DEFAULT NULL COMMENT 'RD_LEFT04',
  `rd_right04` double DEFAULT NULL COMMENT 'RD_RIGHT04',
  `rd_left05` double DEFAULT NULL COMMENT 'RD_LEFT05',
  `rd_right05` double DEFAULT NULL COMMENT 'RD_RIGHT05',
  `rd_left06` double DEFAULT NULL COMMENT 'RD_LEFT06',
  `rd_right06` double DEFAULT NULL COMMENT 'RD_RIGHT06',
  `rd_left07` double DEFAULT NULL COMMENT 'RD_LEFT07',
  `rd_right07` double DEFAULT NULL COMMENT 'RD_RIGHT07',
  `rd_left08` double DEFAULT NULL COMMENT 'RD_LEFT08',
  `rd_right08` double DEFAULT NULL COMMENT 'RD_RIGHT08',
  `rd_left09` double DEFAULT NULL COMMENT 'RD_LEFT09',
  `rd_right09` double DEFAULT NULL COMMENT 'RD_RIGHT09',
  `rd_left10` double DEFAULT NULL COMMENT 'RD_LEFT10',
  `rd_right10` double DEFAULT NULL COMMENT 'RD_RIGHT10',
  `rd_left11` double DEFAULT NULL COMMENT 'RD_LEFT11',
  `rd_right11` double DEFAULT NULL COMMENT 'RD_RIGHT11',
  `rd_left12` double DEFAULT NULL COMMENT 'RD_LEFT12',
  `rd_right12` double DEFAULT NULL COMMENT 'RD_RIGHT12',
  `rd_left13` double DEFAULT NULL COMMENT 'RD_LEFT13',
  `rd_right13` double DEFAULT NULL COMMENT 'RD_RIGHT13',
  `rd_left14` double DEFAULT NULL COMMENT 'RD_LEFT14',
  `rd_right14` double DEFAULT NULL COMMENT 'RD_RIGHT14',
  `rd_left15` double DEFAULT NULL COMMENT 'RD_LEFT15',
  `rd_right15` double DEFAULT NULL COMMENT 'RD_RIGHT15',
  `rd_left16` double DEFAULT NULL COMMENT 'RD_LEFT16',
  `rd_right16` double DEFAULT NULL COMMENT 'RD_RIGHT16',
  `rd_left17` double DEFAULT NULL COMMENT 'RD_LEFT17',
  `rd_right17` double DEFAULT NULL COMMENT 'RD_RIGHT17',
  `rd_left18` double DEFAULT NULL COMMENT 'RD_LEFT18',
  `rd_right18` double DEFAULT NULL COMMENT 'RD_RIGHT18',
  `rd_left19` double DEFAULT NULL COMMENT 'RD_LEFT19',
  `rd_right19` double DEFAULT NULL COMMENT 'RD_RIGHT19',
  `rd_left20` double DEFAULT NULL COMMENT 'RD_LEFT20',
  `rd_right20` double DEFAULT NULL COMMENT 'RD_RIGHT20',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_rqi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `ri` double DEFAULT NULL COMMENT 'RI',
  `ri01` double DEFAULT NULL COMMENT 'RI01',
  `ri02` double DEFAULT NULL COMMENT 'RI02',
  `ri03` double DEFAULT NULL COMMENT 'RI03',
  `ri04` double DEFAULT NULL COMMENT 'RI04',
  `ri05` double DEFAULT NULL COMMENT 'RI05',
  `ri06` double DEFAULT NULL COMMENT 'RI06',
  `ri07` double DEFAULT NULL COMMENT 'RI07',
  `ri08` double DEFAULT NULL COMMENT 'RI08',
  `ri09` double DEFAULT NULL COMMENT 'RI09',
  `ri10` double DEFAULT NULL COMMENT 'RI10',
  `ri11` double DEFAULT NULL COMMENT 'RI11',
  `ri12` double DEFAULT NULL COMMENT 'RI12',
  `ri13` double DEFAULT NULL COMMENT 'RI13',
  `ri14` double DEFAULT NULL COMMENT 'RI14',
  `ri15` double DEFAULT NULL COMMENT 'RI15',
  `ri16` double DEFAULT NULL COMMENT 'RI16',
  `ri17` double DEFAULT NULL COMMENT 'RI17',
  `ri18` double DEFAULT NULL COMMENT 'RI18',
  `ri19` double DEFAULT NULL COMMENT 'RI19',
  `ri20` double DEFAULT NULL COMMENT 'RI20',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_sci_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `ljsh_q` varchar(40) DEFAULT NULL COMMENT '路肩损坏轻',
  `ljsh_m` varchar(40) DEFAULT NULL COMMENT '路肩损坏中',
  `ljsh_z` varchar(40) DEFAULT NULL COMMENT '路肩损坏重',
  `bptt_q` varchar(40) DEFAULT NULL COMMENT '边坡坍塌轻',
  `bptt_m` varchar(40) DEFAULT NULL COMMENT '边坡坍塌中',
  `bptt_z` varchar(40) DEFAULT NULL COMMENT '边坡坍塌重',
  `shcg_q` varchar(40) DEFAULT NULL COMMENT '水毁冲沟轻',
  `shcg_m` varchar(40) DEFAULT NULL COMMENT '水毁冲沟中',
  `shcg_z` varchar(40) DEFAULT NULL COMMENT '水毁冲沟重',
  `ljgzwsh_q` varchar(40) DEFAULT NULL COMMENT '路基构造物损坏轻',
  `ljgzwsh_m` varchar(40) DEFAULT NULL COMMENT '路基构造物损坏中',
  `ljgzwsh_z` varchar(40) DEFAULT NULL COMMENT '路基构造物损坏重',
  `lysqs` varchar(40) DEFAULT NULL COMMENT '路缘石缺损',
  `ljcj_q` varchar(40) DEFAULT NULL COMMENT '路基沉降轻',
  `ljcj_m` varchar(40) DEFAULT NULL COMMENT '路基沉降中',
  `ljcj_z` varchar(40) DEFAULT NULL COMMENT '路基沉降重',
  `psbc_q` varchar(40) DEFAULT NULL COMMENT '排水不畅轻',
  `psbc_m` varchar(40) DEFAULT NULL COMMENT '排水不畅中',
  `psbc_z` varchar(40) DEFAULT NULL COMMENT '排水不畅重',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_sfc_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `sri` double DEFAULT NULL COMMENT 'SRI',
  `sfc` double DEFAULT NULL COMMENT 'SFC',
  `sfc01` double DEFAULT NULL COMMENT 'SFC01',
  `sfc02` double DEFAULT NULL COMMENT 'SFC02',
  `sfc03` double DEFAULT NULL COMMENT 'SFC03',
  `sfc04` double DEFAULT NULL COMMENT 'SFC04',
  `sfc05` double DEFAULT NULL COMMENT 'SFC05',
  `sfc06` double DEFAULT NULL COMMENT 'SFC06',
  `sfc07` double DEFAULT NULL COMMENT 'SFC07',
  `sfc08` double DEFAULT NULL COMMENT 'SFC08',
  `sfc09` double DEFAULT NULL COMMENT 'SFC09',
  `sfc10` double DEFAULT NULL COMMENT 'SFC10',
  `sfc11` double DEFAULT NULL COMMENT 'SFC11',
  `sfc12` double DEFAULT NULL COMMENT 'SFC12',
  `sfc13` double DEFAULT NULL COMMENT 'SFC13',
  `sfc14` double DEFAULT NULL COMMENT 'SFC14',
  `sfc15` double DEFAULT NULL COMMENT 'SFC15',
  `sfc16` double DEFAULT NULL COMMENT 'SFC16',
  `sfc17` double DEFAULT NULL COMMENT 'SFC17',
  `sfc18` double DEFAULT NULL COMMENT 'SFC18',
  `sfc19` double DEFAULT NULL COMMENT 'SFC19',
  `sfc20` double DEFAULT NULL COMMENT 'SFC20',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_tci_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `bxqs` varchar(40) DEFAULT NULL COMMENT '标线缺损',
  `bzqs` varchar(40) DEFAULT NULL COMMENT '标志缺损',
  `fhssqs_q` varchar(40) DEFAULT NULL COMMENT '防护设施缺损轻',
  `fhssqs_z` varchar(40) DEFAULT NULL COMMENT '防护设施缺损重',
  `glssh` varchar(40) DEFAULT NULL COMMENT '隔离栅损坏',
  `lhglbs` varchar(40) DEFAULT NULL COMMENT '绿化管理不善',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `project` (
  `project_id` varchar(40) NOT NULL COMMENT '主键, 项目编码',
  `project_name` varchar(40) DEFAULT NULL COMMENT '项目名称',
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `creator` varchar(20) DEFAULT NULL COMMENT '创建人',
  `year` varchar(20) DEFAULT NULL COMMENT '年度',
  `detector` varchar(40) DEFAULT NULL COMMENT '检测单位',
  `cellphone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `state` int(11) DEFAULT NULL COMMENT '0:未锁定, 1:锁定',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `project_parameter` (
  `project_id` varchar(40) NOT NULL COMMENT '主键, 项目编码',
  `road_grade` varchar(20) DEFAULT NULL COMMENT '技术等级',
  `pavement_type` varchar(20) DEFAULT NULL COMMENT '路面类型',
  `param_name` varchar(20) DEFAULT NULL COMMENT '参数名称',
  `param_value` double DEFAULT NULL COMMENT '参数值',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_bci_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `bci` double DEFAULT NULL COMMENT 'BCI 分值',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_pbi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `pb_sum` double DEFAULT NULL COMMENT 'PB 累加',
  `pbi` double DEFAULT NULL COMMENT 'PBI',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_pci_lq_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `dr` double DEFAULT NULL COMMENT '路面破损率',
  `pci` double DEFAULT NULL COMMENT '路面损坏状况指数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_pci_sn_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `dr` double DEFAULT NULL COMMENT '路面破损率',
  `pci` double DEFAULT NULL COMMENT '路面损坏状况指数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_pssi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `pssi` double DEFAULT NULL COMMENT '结构强度指数 PSSI',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_pwi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `mpd_left` double DEFAULT NULL COMMENT 'MPD_LEFT',
  `mpd_center` double DEFAULT NULL COMMENT 'MPD_CENTER',
  `mpd_right` double DEFAULT NULL COMMENT 'MPD_RIGHT',
  `wr` double DEFAULT NULL COMMENT 'WR',
  `pwi` double DEFAULT NULL COMMENT 'PWI',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_rdi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `rdi` double DEFAULT NULL COMMENT '路面车辙深度指数 RDI',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_rqi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `ri` double DEFAULT NULL COMMENT 'RI',
  `iri` double DEFAULT NULL COMMENT '国际平整度指数 IRI',
  `rqi` double DEFAULT NULL COMMENT '路面行驶质量指数 RQI',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_sci_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `sci` double DEFAULT NULL COMMENT 'SCI 分值',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_sfc_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `sri` double DEFAULT NULL COMMENT 'SRI',
  `sfc` double DEFAULT NULL COMMENT 'SFC',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `result_tci_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `unit_code` varchar(40) DEFAULT NULL COMMENT '路段编码',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `bxqs` varchar(40) DEFAULT NULL COMMENT '标线缺损',
  `bzqs` varchar(40) DEFAULT NULL COMMENT '标志缺损',
  `fhssqs_q` varchar(40) DEFAULT NULL COMMENT '防护设施缺损轻',
  `fhssqs_z` varchar(40) DEFAULT NULL COMMENT '防护设施缺损重',
  `glssh` varchar(40) DEFAULT NULL COMMENT '隔离栅损坏',
  `lhglbs` varchar(40) DEFAULT NULL COMMENT '绿化管理不善',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `stats_district_compose_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `project_id` varchar(40) DEFAULT NULL COMMENT '项目编码',
  `district` varchar(40) DEFAULT NULL COMMENT '所属政区/区域',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `length_grade1` decimal(32,3) DEFAULT NULL COMMENT '一级公路长度',
  `length_grade2` decimal(32,3) DEFAULT NULL COMMENT '二级公路长度',
  `length_grade3` decimal(32,3) DEFAULT NULL COMMENT '三级公路长度',
  `length_grade4` decimal(32,3) DEFAULT NULL COMMENT '四级公路长度',
  `length_type_lq` decimal(32,3) DEFAULT NULL COMMENT '沥青公路长度',
  `length_type_sn` decimal(32,3) DEFAULT NULL COMMENT '水泥公路长度',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `stats_district_detail_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `project_id` varchar(40) DEFAULT NULL COMMENT '项目编码',
  `road_code` varchar(40) DEFAULT NULL COMMENT '路线编码',
  `road_name` varchar(40) DEFAULT NULL COMMENT '路线名称',
  `district` varchar(40) DEFAULT NULL COMMENT '所属政区/区域',
  `line_dir` varchar(2) DEFAULT NULL COMMENT '调查方向',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `pqi` double DEFAULT NULL COMMENT 'PQI',
  `pci` double DEFAULT NULL COMMENT 'PCI',
  `rqi` double DEFAULT NULL COMMENT 'RQI',
  `rdi` double DEFAULT NULL COMMENT 'RDI',
  `pbi` double DEFAULT NULL COMMENT 'PBI',
  `pwi` double DEFAULT NULL COMMENT 'PWI',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `stats_district_pqi_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `project_id` varchar(40) DEFAULT NULL COMMENT '项目编码',
  `district` varchar(40) DEFAULT NULL COMMENT '所属政区/区域',
  `metrics_name` varchar(40) DEFAULT NULL COMMENT '指标名称',
  `average` decimal(10,2) DEFAULT NULL COMMENT '均值',
  `percent_good` decimal(10,2) DEFAULT NULL COMMENT '优良路率',
  `percent_bad` decimal(10,2) DEFAULT NULL COMMENT '次差路率',
  `excellent` decimal(10,2) DEFAULT NULL COMMENT '优(公里)',
  `good` decimal(10,2) DEFAULT NULL COMMENT '良(公里)',
  `general` decimal(10,2) DEFAULT NULL COMMENT '中(公里)',
  `fair` decimal(10,2) DEFAULT NULL COMMENT '次(公里)',
  `bad` decimal(10,2) DEFAULT NULL COMMENT '差(公里)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `stats_district_pqi_summary_1000` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键, 自增',
  `project_id` varchar(40) DEFAULT NULL COMMENT '项目编码',
  `district` varchar(40) DEFAULT NULL COMMENT '所属政区/区域',
  `avg_pqi` decimal(10,2) DEFAULT NULL COMMENT '平均 PQI',
  `percent_good_pqi` decimal(10,2) DEFAULT NULL COMMENT '优良 PQI 路率',
  `percent_bad_pqi` decimal(10,2) DEFAULT NULL COMMENT '次差 PQI 路率',
  `avg_pci` decimal(10,2) DEFAULT NULL COMMENT '平均 PCI',
  `percent_good_pci` decimal(10,2) DEFAULT NULL COMMENT '优良 PCI 路率',
  `percent_bad_pci` decimal(10,2) DEFAULT NULL COMMENT '次差 PCI 路率',
  `avg_rqi` decimal(10,2) DEFAULT NULL COMMENT '平均 RQI',
  `percent_good_rqi` decimal(10,2) DEFAULT NULL COMMENT '优良 RQI 路率',
  `percent_bad_rqi` decimal(10,2) DEFAULT NULL COMMENT '次差 RQI 路率',
  `avg_rdi` decimal(10,2) DEFAULT NULL COMMENT '平均 RDI',
  `percent_good_rdi` decimal(10,2) DEFAULT NULL COMMENT '优良 RDI 路率',
  `percent_bad_rdi` decimal(10,2) DEFAULT NULL COMMENT '次差 RDI 路率',
  `avg_pwi` decimal(10,2) DEFAULT NULL COMMENT '平均 PWI',
  `percent_good_pwi` decimal(10,2) DEFAULT NULL COMMENT '优良 PWI 路率',
  `percent_bad_pwi` decimal(10,2) DEFAULT NULL COMMENT '次差 PWI 路率',
  `avg_pbi` decimal(10,2) DEFAULT NULL COMMENT '平均 PBI',
  `percent_good_pbi` decimal(10,2) DEFAULT NULL COMMENT '优良 PBI 路率',
  `percent_bad_pbi` decimal(10,2) DEFAULT NULL COMMENT '次差 PBI 路率',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `stats_unit_detail_1000` (
  `unit_code` varchar(40) NOT NULL COMMENT '路段编码',
  `year` varchar(100) DEFAULT NULL COMMENT '年度信息',
  `project_id` varchar(40) DEFAULT NULL COMMENT '项目信息',
  `road_code` varchar(40) DEFAULT NULL COMMENT '路线 ID',
  `start_stake` varchar(40) DEFAULT NULL COMMENT '起点桩号',
  `end_stake` varchar(40) DEFAULT NULL COMMENT '终点桩号',
  `length` decimal(32,3) DEFAULT NULL COMMENT '路段长度',
  `pqi_tc_code` varchar(20) DEFAULT NULL COMMENT 'PQI 等级',
  `pqi` double DEFAULT NULL COMMENT 'PQI',
  `pci_tc_code` varchar(20) DEFAULT NULL COMMENT 'PCI 等级',
  `pci` double DEFAULT NULL COMMENT 'PCI',
  `rqi_tc_code` varchar(20) DEFAULT NULL COMMENT 'RQI 等级',
  `rqi` double DEFAULT NULL COMMENT 'RQI',
  `rdi_tc_code` varchar(20) DEFAULT NULL COMMENT 'RDI 等级',
  `rdi` double DEFAULT NULL COMMENT 'RDI',
  `pbi_tc_code` varchar(20) DEFAULT NULL COMMENT 'PBI 等级',
  `pbi` double DEFAULT NULL COMMENT 'PBI',
  `pwi_tc_code` varchar(20) DEFAULT NULL COMMENT 'PWI 等级',
  `pwi` double DEFAULT NULL COMMENT 'PWI',
  `bci_tc_code` varchar(20) DEFAULT NULL COMMENT 'BCI 等级',
  `bci` double DEFAULT NULL COMMENT 'BCI',
  `mqi_tc_code` varchar(20) DEFAULT NULL COMMENT 'MQI 等级',
  `mqi` double DEFAULT NULL COMMENT 'MQI',
  `sci_tc_code` varchar(20) DEFAULT NULL COMMENT 'SCI 等级',
  `sci` double DEFAULT NULL COMMENT 'SCI',
  `sri_tc_code` varchar(20) DEFAULT NULL COMMENT 'SRI 等级',
  `sri` double DEFAULT NULL COMMENT 'SRI',
  `tci_tc_code` varchar(20) DEFAULT NULL COMMENT 'TCI 等级',
  `tci` double DEFAULT NULL COMMENT 'TCI',
  `tdi_tc_code` varchar(20) DEFAULT NULL COMMENT 'TDI 等级',
  `tdi` varchar(40) DEFAULT NULL COMMENT 'TDI',
  `pssi_tc_code` varchar(20) DEFAULT NULL COMMENT 'PSSI 等级',
  `pssi` double DEFAULT NULL COMMENT 'PSSI',
  PRIMARY KEY (`unit_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

